In [2]:
import numpy as np

In [5]:
a=np.array([5,6,9])
a[0]
a.ndim

1

In [3]:
a[1]

6

In [7]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]],dtype=np.float64)
print(a.ndim)
print(a.itemsize)

2
8


In [9]:
a

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [10]:
  a.size
    

9

In [11]:
a.shape

(3, 3)

In [12]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]],dtype=complex)
a

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j],
       [7.+0.j, 8.+0.j, 9.+0.j]])

In [14]:
np.ones((3,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [17]:
np.zeros( (3,6) )

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [18]:
l=range(5)
l

range(0, 5)

In [22]:
l[0],l[1]

(0, 1)

In [20]:
l[1]

1

In [21]:
np.arange(1,5)

array([1, 2, 3, 4])

generates number b/w 1 and 5 with gap of 2

In [23]:
np.arange(1,5,2) 

array([1, 3])

generates 10 linearly spaced numbers b/w 1 and 5

In [26]:
np.linspace(1,5,10) 

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [28]:
 a

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j],
       [7.+0.j, 8.+0.j, 9.+0.j]])

In [30]:
a.reshape(9,1)

array([[1.+0.j],
       [2.+0.j],
       [3.+0.j],
       [4.+0.j],
       [5.+0.j],
       [6.+0.j],
       [7.+0.j],
       [8.+0.j],
       [9.+0.j]])

In [31]:
a.reshape(1,9)

array([[1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j, 6.+0.j, 7.+0.j, 8.+0.j,
        9.+0.j]])

 functions don't alter shape of original array

In [34]:
a

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j],
       [7.+0.j, 8.+0.j, 9.+0.j]])

flatten array using "ravel()"function and make it 1-D

In [33]:
a.ravel()

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j, 6.+0.j, 7.+0.j, 8.+0.j,
       9.+0.j])

In [35]:
a.max()

(9+0j)

In [36]:
a.min()

(1+0j)

In [37]:
a.sum()

(45+0j)

 Axis-0 are Columns and Axis-1 are Rows

In [38]:
a.sum(axis=0)

array([12.+0.j, 15.+0.j, 18.+0.j])

In [39]:
a.sum(axis=1)

array([ 6.+0.j, 15.+0.j, 24.+0.j])

In [9]:
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

 Standard Deviation of all numbers in array

In [53]:
y=np.std(a)
print(y)

2.581988897471611


In [54]:
y=np.std(a)
formatted_y = "%.2f"%y
print(formatted_y)

2.58


In [56]:
c=np.array([[1,2],[3,4]])
d=np.array([[5,6],[7,8]])

In [57]:
c+d

array([[ 6,  8],
       [10, 12]])

In [58]:
c*d

array([[ 5, 12],
       [21, 32]])

In [59]:
c/d

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

DOT() do matrix product of two arrays

In [61]:
c.dot(d)

array([[19, 22],
       [43, 50]])

Thank You