In [1]:
import numpy as np

In [2]:
np.ones((3,3),dtype='i8')

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int64)

In [3]:
np.ones((3,3),dtype='f8')

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [5]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [6]:
A=np.eye(3)

In [8]:
A

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
B=np.where(A==0,100,200)

In [10]:
B

array([[200, 100, 100],
       [100, 200, 100],
       [100, 100, 200]])

In [11]:
B[0]

array([200, 100, 100])

In [12]:
C=B[0:2]

In [13]:
C

array([[200, 100, 100],
       [100, 200, 100]])

In [15]:
C[:,0]

array([200, 100])

In [16]:
D=C[0,0]

In [17]:
D

200

In [18]:
D.ndim

0

In [19]:
D.shape

()

In [20]:
E=C[0:,0:1]

In [21]:
E

array([[200],
       [100]])

In [22]:
E.ndim

2

In [23]:
E.shape

(2, 1)

In [24]:
A1=np.arange(1,10).reshape(3,3)

In [25]:
A1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
A2=np.arange(11,20).reshape(3,3)

In [27]:
A2

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [28]:
A12=np.concatenate(A1,A2)

TypeError: only integer scalar arrays can be converted to a scalar index

In [29]:
A12=np.concatenate((A1,A2))

In [30]:
A12

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [31]:
A13=np.concatenate((A1,A2),axis=0)

In [32]:
A13

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [33]:
A14=np.concatenate((A1,A2),axis=1)

In [34]:
A14

array([[ 1,  2,  3, 11, 12, 13],
       [ 4,  5,  6, 14, 15, 16],
       [ 7,  8,  9, 17, 18, 19]])

In [35]:
A15=np.vstack((A1,A2))

In [36]:
A15

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [38]:
A16=np.vstack((A1,A2),axis=0)

TypeError: vstack() got an unexpected keyword argument 'axis'

In [39]:
A17=np.vstack(A1,A2)

TypeError: vstack() takes 1 positional argument but 2 were given

In [40]:
A17=np.vstack((A1,A2))

In [41]:
A17

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [42]:
A18=np.hstack((A1,A2))

In [43]:
A18

array([[ 1,  2,  3, 11, 12, 13],
       [ 4,  5,  6, 14, 15, 16],
       [ 7,  8,  9, 17, 18, 19]])

In [44]:
B1=A18.T

In [45]:
B1

array([[ 1,  4,  7],
       [ 2,  5,  8],
       [ 3,  6,  9],
       [11, 14, 17],
       [12, 15, 18],
       [13, 16, 19]])

In [46]:
A18

array([[ 1,  2,  3, 11, 12, 13],
       [ 4,  5,  6, 14, 15, 16],
       [ 7,  8,  9, 17, 18, 19]])

In [47]:
A18.T

array([[ 1,  4,  7],
       [ 2,  5,  8],
       [ 3,  6,  9],
       [11, 14, 17],
       [12, 15, 18],
       [13, 16, 19]])

In [48]:
A18.swapaxes(0,1)

array([[ 1,  4,  7],
       [ 2,  5,  8],
       [ 3,  6,  9],
       [11, 14, 17],
       [12, 15, 18],
       [13, 16, 19]])

In [49]:
A18

array([[ 1,  2,  3, 11, 12, 13],
       [ 4,  5,  6, 14, 15, 16],
       [ 7,  8,  9, 17, 18, 19]])

In [50]:
A18.swapaxes(1,0)

array([[ 1,  4,  7],
       [ 2,  5,  8],
       [ 3,  6,  9],
       [11, 14, 17],
       [12, 15, 18],
       [13, 16, 19]])

In [51]:
A18

array([[ 1,  2,  3, 11, 12, 13],
       [ 4,  5,  6, 14, 15, 16],
       [ 7,  8,  9, 17, 18, 19]])

In [52]:
A18.swapaxes()

TypeError: swapaxes() takes exactly 2 arguments (0 given)

In [53]:
G=np.random.randint(10,110,10)

In [54]:
G

array([103,  23,  51,  57,  74,  14,  45,  57,  23,  65])

In [55]:
G.size

10

In [56]:
H=G.reshape(2,-1)

In [57]:
H

array([[103,  23,  51,  57,  74],
       [ 14,  45,  57,  23,  65]])

In [58]:
H.sort()

In [59]:
H

array([[ 23,  51,  57,  74, 103],
       [ 14,  23,  45,  57,  65]])

In [60]:
H.sort(axis=1)

In [61]:
H

array([[ 23,  51,  57,  74, 103],
       [ 14,  23,  45,  57,  65]])

In [62]:
H.sort(axis=0)

In [63]:
H

array([[ 14,  23,  45,  57,  65],
       [ 23,  51,  57,  74, 103]])

In [66]:
H[::-1]

array([[ 23,  51,  57,  74, 103],
       [ 14,  23,  45,  57,  65]])

In [68]:
H

array([[ 14,  23,  45,  57,  65],
       [ 23,  51,  57,  74, 103]])

In [67]:
H[:,::-1]

array([[ 65,  57,  45,  23,  14],
       [103,  74,  57,  51,  23]])

In [73]:
from numpy import linalg

In [74]:
A=np.arange(1,10).reshape(3,3)

In [75]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [76]:
linalg.det(A)

0.0

In [77]:
H

array([[ 14,  23,  45,  57,  65],
       [ 23,  51,  57,  74, 103]])

In [78]:
linalg.det(H)

LinAlgError: Last 2 dimensions of the array must be square

In [79]:
C=np.eye(3,3)

In [80]:
C

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [81]:
linalg.det(C)

1.0

In [83]:
N=np.random.rand(3,3)

In [84]:
N

array([[0.24328718, 0.09797536, 0.39609087],
       [0.94465086, 0.98649864, 0.72231883],
       [0.44566882, 0.90513668, 0.15145257]])

In [85]:
linalg.det(N)

0.05934170491336679

In [86]:
linalg.inv(N)

array([[-8.49974754,  5.79150456, -5.39205365],
       [ 3.01381928, -2.35380632,  3.34396646],
       [ 6.9999078 , -2.97503395,  2.48476115]])

In [88]:
N@linalg.inv(N)

array([[ 1.00000000e+00, -3.14617276e-16, -2.17821238e-17],
       [-1.23217374e-15,  1.00000000e+00, -3.09299323e-16],
       [-1.97494654e-16, -9.59698299e-17,  1.00000000e+00]])

In [89]:
N=np.random.randint(10,size=(3,3))